[[constraint]]
    name="github.com/rs/zerolog"
    version="v1.8.0"

[[constraint]]
    name="github.com/spf13/cobra"
    version="v0.0.3"

[[constraint]]
    name="github.com/nalej/derrors"
    version="=v2.0.0"

[[constraint]]
    name="github.com/nalej/grpc-utils"
    version="=v1.3.1"

[[constraint]]
    name="github.com/nalej/grpc-organization-go"
    version="=v0.0.29"

[[constraint]]
  name="github.com/nalej/grpc-application-go"
  version="=v0.0.80"

[[constraint]]
    name="github.com/nalej/grpc-infrastructure-go"
    version="=v0.0.37"

[[constraint]]
    name="github.com/nalej/grpc-user-go"
    version="=v0.0.30"

[[constraint]]
    name="github.com/nalej/grpc-role-go"
    version="=v0.0.24"

[[constraint]]
    name="github.com/nalej/grpc-common-go"
    version="=v0.0.30"

[[constraint]]
    name="github.com/nalej/grpc-device-go"
    version="=v0.0.34"

[[constraint]]
    name="github.com/nalej/grpc-inventory-go"
    version="=v0.0.10"

[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"

[[constraint]]
    name="github.com/onsi/ginkgo"
    version="v1.6.0"

[[constraint]]
    name="github.com/onsi/gomega"
    version="v1.4.2"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"