kind: Service
apiVersion: v1
metadata:
  name: system-model
  labels:
    cluster: management
    component: system-model
  namespace: __NPH_NAMESPACE
spec:
  selector:
    cluster: management
    component: system-model
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8800
      targetPort: 8800
