###
# System Model
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: system-model
  name: system-model
  namespace: nalej
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: system-model
  template:
    metadata:
      labels:
        cluster: management
        component: system-model
    spec:
      containers:
      - name: system-model
        image: nalejregistry.azurecr.io/nalej/system-model:VERSION
        imagePullPolicy: IfNotPresent
        args:
          - "run"
          - "--debug"
        securityContext:
          runAsUser: 2000
      imagePullSecrets:
      - name: nalej-registry
