###
# Application example
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: application
    component: example
  name: example
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: application
      component: example
  template:
    metadata:
      labels:
        app: application
        component: example
    spec:
      containers:
      - name: example
        image: nalej/example-app:v0.0.1
        imagePullPolicy: Always
        securityContext:
          runAsUser: 2000
      imagePullSecrets:
      - name: myregistrykey
