variables: 
  - template: variables/global-variables.yaml@ci_templates
  - template: variables/go-variables.yaml@ci_templates
  - template: variables/k8s-variables.yaml@ci_templates
  - template: variables/nalej-variables.yaml@ci_templates
  - template: variables/git-variables.yaml@ci_templates

resources:
  repositories:
    - repository: ci_templates
      type: github
      name: nalej/ci-templates
      endpoint: nalej
      ref: 'refs/heads/feature/NP-2334_New_Pipeline_Structure'

stages:
- stage: 'Start_Slack'
  jobs:
  - job: MainWorkflow
    pool:
      vmImage: 'ubuntu-latest'    
    steps:
    - template: slack/build/start.yaml@ci_templates
      parameters:
        author: $(authorName)
        repository: $(Build.Repository.Name)
        branch: $(Build.SourceBranch)
        commit: $(Build.SourceVersionMessage)
        buildUrl: $(buildUrl)$(Build.BuildId)
        slackWebhook: $(slackBuilds)

- stage: 'Binary_Build'
  condition: eq(variables['language'], 'golang')
  dependsOn: 'Start_Slack'
  jobs:
  - job: MainWorkflow
    pool:
      vmImage: 'ubuntu-latest'  
    steps:
    - template: steps/go_main.yaml@ci_templates

- stage: 'Image_Build'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  dependsOn: 'Binary_Build'
  jobs:
  - job: MainWorkflow
    pool:
      vmImage: 'ubuntu-latest'  
    steps:
    - template: steps/docker_main.yaml@ci_templates

- stage: 'Finish_Slack'
  condition: always()
  jobs:
  - job: MainWorkflow
    pool:
      vmImage: 'ubuntu-latest'  
    steps: 
    - template: slack/build/finish.yaml@ci_templates
      parameters:
        author: $(authorName)
        repository: $(Build.Repository.Name)
        branch: $(Build.SourceBranch)
        commit: $(Build.SourceVersionMessage)
        buildUrl: $(buildUrl)$(Build.BuildId)
        slackWebhook: $(slackBuilds)
        modulePath: $(modulePath)
    
    - template: slack/build/failed.yaml@ci_templates
      parameters:
        author: $(authorName)
        repository: $(Build.Repository.Name)
        branch: $(Build.SourceBranch)
        commit: $(Build.SourceVersionMessage)
        buildUrl: $(buildUrl)$(Build.BuildId)
        slackWebhook: $(slackCIFailed)
        modulePath: $(modulePath)
